# Generated by Django 4.2.2 on 2023-06-20 08:02

import MyPlantApp.plants.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plant_type",
                    models.CharField(
                        choices=[
                            ("Outdoor Plants", "Outdoor Plants"),
                            ("Indoor Plants", "Indoor Plants"),
                        ],
                        max_length=14,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.MinLengthValidator(2),
                            MyPlantApp.plants.validators.plant_name_only_letters,
                        ],
                    ),
                ),
                ("image_url", models.URLField(blank=True, null=True)),
                ("description", models.TextField()),
                (
                    "price",
                    models.FloatField(
                        validators=[MyPlantApp.plants.validators.plant_price_validator]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=10,
                        validators=[django.core.validators.MinLengthValidator(2)],
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        max_length=20,
                        validators=[MyPlantApp.plants.validators.check_name],
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        max_length=20,
                        validators=[MyPlantApp.plants.validators.check_name],
                    ),
                ),
                ("profile_picture", models.URLField(blank=True, null=True)),
            ],
        ),
    ]
